### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by hormoskunk** [kibook/pmms#102]
Has anybody missing icons in pmms as well? It happened maybe 4 days ago and I've tried even first untouched version of pmms and still have same problem.
![missing icons](https://github.com/user-attachments/assets/52e96a0a-bb5e-425a-9247-3e214c70ead0)

**Comment by DbGottEm** [comment]
yeah having the same issue, downloaded and installed today doesnt look like there are any archives for updates so i dont think its an update issue.. Hopefully the owner responds with a fix.. @kibook

**Comment by alexpumasage** [comment]
It looks like there is an issue with https://kit.fontawesome.com/5537a772c3.js in index.html

**Comment by hormoskunk** [comment]
Yeah, I've just just made a new kit with free icons and it works... You have to all change link in 5th line in index.html with this my new one...
`https://kit.fontawesome.com/d284cd84f9.js`

**Comment by hormoskunk** [comment]
Yeah, I've just just made a new kit with free icons and it works... You have to all change link in 5th line in index.html with this my new one...
`https://kit.fontawesome.com/d284cd84f9.js`

**Comment by DbGottEm** [comment]
Worked like a charm! thanks @hormoskunk

**Comment by alexpumasage** [comment]
@hormoskunk advice: don't share your link, it's limited to 10k views for free 
Everyone should create a link

**Comment by hormoskunk** [comment]
I didn't know that... but at least I've helped others to get icons back and if we exceed 10k views I will make new one only for myself next time 😄

**Comment by Legacy-TacticalGamingInteractive** [comment]
> Yeah, I've just just made a new kit with free icons and it works... You have to all change link in 5th line in index.html with this my new one... `https://kit.fontawesome.com/d284cd84f9.js`

im making my own as well but what did you put for your kit domain? mine are still invisible.
you usin font awesome 5?
