### ISSUE TITLE
Interface don't show icons

### ISSUE THREAD

**Issue by Sp1r1To** [kibook/pmms#104]
For some reason the icons on ui don't show, all works but without icons
![Captura de pantalla 2024-09-12 154418](https://github.com/user-attachments/assets/58fb4eca-96cc-421d-86c1-48a696efa408)

**Comment by ChrisIrna** [comment]
Having the same issue after having changed the artifact version to 7290... Did not find a solution ...

**Comment by sadoj-kuro** [comment]
you need to update the line 3 in the pmms/ui/index.html

just put that

<script src="https://kit.fontawesome.com/d7599e58fc.js" crossorigin="anonymous"></script>

**Comment by Sp1r1To** [comment]
Work! Thank you so much, it's an amazing script :)
