### ISSUE TITLE
Weird behaviour

### ISSUE THREAD

**Issue by Thercious** [kibook/pmms#26]
Sound doesn't play for me when I play a video, but it played for another player when I tested it. Sometimes the image appears, but sound is usually what doesn't play for me.

Sometimes, restarting the server made the plugin work again, restarting the game worked on others, but right now, nothing seems to work.

Tried updating both pmms and httpmanager, but nothing changed for me.

Running it on build 4947 on Linux, with game version 2372.

This is the console error that I get every time I play a video through pmms:
![image](https://user-images.githubusercontent.com/36479118/144730603-8d44fd96-b186-47c7-b073-dbadbc48146b.png)

**Comment by kibook** [comment]
Does this only occur when playing videos from YouTube, or does it also occur when playing from other sources (such as Twitch streams or direct video files like https://fivem.khzae.net/pie.webm for example)?

Are you using the Release or Canary version of FiveM? Have you tried it on both?

The second error seems to be a common message received from YouTube and appears even when a video plays successfully. I'm not sure about the first error. It seems like the instance of Chromium inside of FiveM is blocking the request to YouTube for some reason, but I'm not sure why that would only happen to certain players like yourself and not everyone.
