### ISSUE TITLE
Oh noo look what i did *giggles*

### ISSUE THREAD

**Issue by ShaAlexander** [kibook/pmms#28]
![20211220214702_1](https://user-images.githubusercontent.com/91032578/146830830-0c23dd2e-c890-4244-8185-a9dcc7949714.jpg)

I might have created a wormhole! But your scripts rock! 
Combined the live map with an YouTube stream, and now it's shown on one of those screens I told you about!

**Comment by kibook** [comment]
Very nice, but if you want to create a wormhole, you have to stream yourself playing FiveM to YouTube or Twitch, and then play that stream with pmms! 😄 

This would probably be better suited for the [discussions](https://github.com/kibook/pmms/discussions), though. 😉

**Comment by ShaAlexander** [comment]
> Very nice, but if you want to create a wormhole, you have to stream yourself playing FiveM to YouTube or Twitch, and then play that stream with pmms! 😄
> 
> This would probably be better suited for the [discussions](https://github.com/kibook/pmms/discussions/categories/show-and-tell), though. 😉

Yeah, but make sure you never step in to that hole I did that once, and now I'm forever stuck in my RP Sever :( help, let me out of here.
