### ISSUE TITLE
Sound Emitters For Mpsecurity / 2545 - FiveM

### ISSUE THREAD

**Issue by TayMcKenzieNZ** [kibook/pmms#30]
https://github.com/DurtyFree/gta-v-data-dumps/blob/master/staticEmitters.json

**Comment by Jamie9192** [comment]
https://fivem-sound-emitter-search.pages.dev/ 

I utilised this list, and made a search function, to order the list dependant on distance from entered coords. 

Helpful for finding the ones with unexpected names, such as "collision"

**Comment by TayMcKenzieNZ** [comment]
You should probably credit DurtyFree's GitHub though 🤔 @Jamie9192

**Comment by Jamie9192** [comment]
Oh, I thought it was you that done the work, I'll get that sorted :)
