### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by FritLP** [kibook/pmms#31]
Good day,
is it possible to improve the resolution in any way?

Greetings

**Comment by kibook** [comment]
The quality depends on a few factors. When using a render target, the resolution is limited to that of the texture, which are usually very small (the biggest I've seen is 512x512). I'm not certain if it's possible to replace the texture with a larger one or make your own object with a custom texture.

If you use a 3D scaleform screen instead, then the max resolution will be determined by the `Config.dui.screenWidth` and `Config.dui.screenHeight` settings in config.lua, which is 1280x720 by default. You can increase this, although keep in mind it will cause the scaleform settings to differ, i.e. a larger resolution will require the scaleform scale to be smaller to achieve the same in-game screen size.
