### ISSUE TITLE
youtube playlist stop after first video...

### ISSUE THREAD

**Issue by ccking91** [kibook/pmms#32]
dont know when to start...
youtube playlist stop after first video...
it was fine before...
continute play next video...

this is error when video end...
![Capture](https://user-images.githubusercontent.com/87742755/150129288-efc9a448-895a-4037-af40-e985cb80d573.PNG)

**Comment by kibook** [comment]
There is no support for playlists currently, the `list=...` part of a YouTube URL is simply ignored by MediaElement.js as far as I am aware.

If they did work for you somehow despite this, and that changed without updating pmms, then it's possibly a change with YouTube itself. If you did update pmms to a newer commit and that seemed to cause this to happen, can you find out which commit you were using before and test whether it still works if you revert back to that?

**Comment by ccking91** [comment]
maybe is youtube change something,,,
because im not update pmms...
hope this feature will work in future...
thanks for reply...

**Comment by TayMcKenzieNZ** [comment]
I've never been able to do playlists, but rather add the links one by one, until someone else stops PMMS or plays a different song, which is annoying. Unfortunately at this time, Kibook is unaware of how to do playlists.
