### ISSUE TITLE
Disable DUI and only use to stream audio?

### ISSUE THREAD

**Issue by Duderocktv** [kibook/pmms#42]
Am I missing something here?
Its asking me to initilize a DUI browser and all this stuff but all I'm trying to do is stream audio, not video.

**Comment by Duderocktv** [comment]
Note: Everything still works! It just gives me an error in the console

**Comment by kibook** [comment]
What is asking you to initialize a DUI browser? That should all happen behind the scenes. Could you provide an example of what you are trying to play, and what errors you are receiving?
