### ISSUE TITLE
Links are all unavailable..?

### ISSUE THREAD

**Issue by EagLeTaLoN713** [kibook/pmms#46]
All links dont seem to play on the player.  Just get VIDEO unavailable.

**Comment by kibook** [comment]
Can you provide an example URL that does not play?

**Comment by EagLeTaLoN713** [comment]
https://youtu.be/UiI7G5VR5xY  No youtube URL's play.  

https://gyazo.com/6b52a12102beb124d68791a5b474f5e3

**Comment by EagLeTaLoN713** [comment]
Seems some links work, and some don't. Maybe copyright or something?    Anyway, Ive seem to have gotten video to work, but no volume or audio transmitting. 

https://i.gyazo.com/d07cdd2c5f36e95bb6d0f69ae7a293e2.jpg

**Comment by kibook** [comment]
YouTube doesn't really like NUI, it often blocks videos when you attempt to embed them there. DUI is a lot more reliable, but unfortunately RedM does not support it yet, only FiveM does.

Some YouTube videos will work, at least as of the last time I tried it. The only thing you can really do is download the video from YouTube and upload somewhere you can get a direct link to it. You can place video files in the `http/media` folder inside the pmms resource folder, and then you can play these by specifying the only the name of the video file in the URL field. For example, if you place `myvideo.mp4` in `http/media`, then you can play it in pmms by entering `myvideo.mp4` in the URL field.

**Comment by EagLeTaLoN713** [comment]
Nevermind, had something from redm muted in my mixer
