### ISSUE TITLE
Synced volume without reloading the video

### ISSUE THREAD

**Issue by Kurosar** [kibook/pmms#5]
Hello again,

I have a suggestion for PMMS.
The ability to sync the audio volume with other listeners without reloading the entire video.

Currently, it is not possible, if we change the volume we have to reload the entire video :/

Best regards.

**Comment by kibook** [comment]
Every player can adjust their own volume via the red slider in the UI. Originally, the ability to adjust both your personal volume and the volume of the media player was included in the UI, but it tended to be confusing for people, who would just use the synced volume. This meant some people would make it really quiet, which meant you had to turn your personal volume to 100, but then another person who had their volume at 50 would make the next thing really loud.

The intention is for media players to almost always play at 100% volume and for each player to pick a volume that works for them. The ability to set the volume for an individual media player was left in as an "advanced" setting for the rarer case where you really do want a specific media player to be quieter overall.

I might still try and add this, mainly for the ability to adjust other advanced settings like attenuation and range without having to stop the media player. But I think it's still better to leave the synced volume at 100 in most cases, and let players pick a volume that's best for them.

**Comment by kibook** [comment]
2361060 adds the ability to set the volume, attenuation and range of an active media player through the advanced settings area. Select it from the drop-down list to change those values for it.
