### ISSUE TITLE
Video quality

### ISSUE THREAD

**Issue by hugochugo** [kibook/pmms#6]
I don't know if there's a setting I'm missing but is there a way to make the video quality better on some of the tv props? Also doesn't auto enter mature audience streams on twitch.

**Comment by kibook** [comment]
I believe it's limited by the resolution of the render target texture of the screen. Most are quite small, like 512x256 is the biggest I've seen among the base game textures so far. `Config.dui.screenWidth` and `Config.dui.screenHeight` currently control the size of the DUI browser, but it won't help if the render target texture is small as it just gets scaled down.

It may be possible to use a custom TV model with a higher resolution render target texture, but I haven't tried. Another possibility is adding the ability to draw on a 3D scaleform screen, like https://forum.cfx.re/t/release-generic-dui-2d-3d-renderer/131208.

As for Twitch, I'll try and see if there's a way to make it go past that warning. Could you make a separate issue for that?

**Comment by hugochugo** [comment]
Yes I will, this can be closed it just depends on the tv you use like you said. Awesome resource better then hypnonema and other tv resources. Also way more optimized.

**Comment by kibook** [comment]
Thanks!
