### ISSUE TITLE
Mature audience on twitch

### ISSUE THREAD

**Issue by hugochugo** [kibook/pmms#7]
When viewing a twitch with mature audience it doesn't automatically get by the screen.

**Comment by kibook** [comment]
Added something in af11073 to auto-click the button.

**Comment by hugochugo** [comment]
All is working good now I believe. Any way to get a description on what each button does on the ui?

**Comment by kibook** [comment]
Yeah, it's something I'll add, maybe a help section or tooltips of some kind. If you want, make another issue for that since it's a different topic.
