### ISSUE TITLE
Description of ui buttons

### ISSUE THREAD

**Issue by hugochugo** [kibook/pmms#8]
![image](https://user-images.githubusercontent.com/66925703/126051169-e60bfc13-0ee1-45ea-916c-28008749bfbb.png)

Maybe like an arrow to each button and a description of what it does. Also maybe a little more info on how to get it to play a website on the tv. I see a setting in the config for dui.url but haven't been able to figure it out. Would be good when watching ppv fights since you won't have to stream it on twitch or youtube to show in game.

**Comment by kibook** [comment]
Not all websites will work, there's no universal way to tap into every kind of website out there. Currently YouTube and Twitch are the only special websites that I know work. pmms primarily uses the [MediaElement.js](https://www.mediaelementjs.com) library, which does have support for a few more special sites, but there are additional issues getting them to work with pmms.

This resource does not stream the video or anything to other players. Each player has to be able to access whatever video you're playing on their own, so something like a "ppv fight" or Netflix probably will not be supported.

The `Config.dui.url` setting is the URL of the DUI server that is used to play media. Most people can just use the default server, https://kibook.github.io/pmms, which I host [as part of this repository](https://github.com/kibook/pmms/tree/gh-pages) using GitHub Pages. The only reason to change this is if you wanted to host your own server, for reasons such as:
- the resource is currently under development and things change quickly, so hosting your own server will ensure nothing breaks if you're not using the latest version of the resource
- if you're a developer, you might want to host a custom server with your own modifications
- if you don't like the idea of me potentially being able to see every URL you play, you might want to host a private copy of the server

If you do want to host your own server, it's very simple to do. Simply fork this repository, and then you'll have your own server at `https://<your username>.github.io/pmms`. But for the most part, you should be fine using the default server.

**Comment by kibook** [comment]
96d5faa adds tooltips like these to the UI:

[![](https://i.imgur.com/Bkp9Ichm.jpg)](https://imgur.com/Bkp9Ich)

**Comment by hugochugo** [comment]
awesome job loving it
