### ISSUE TITLE
"Couldn't start resource pmms."

### ISSUE THREAD

**Issue by MerzRP** [kibook/pmms#87]
"Couldn't start resource pmms." I followed installation instructions but everything I try is not working. I even had another developer look into and he wasn't able to see why it wasn't starting.

exec @pmms/permissions.cfg
ensure pmms
ensure sound 

are in the server config file.

Any idea?

**Comment by AndreasFromDanmark** [comment]
You need this
![image](https://github.com/kibook/pmms/assets/35656492/ecab7202-f951-4605-8df9-9513776ce418)
